- name: setup frontend server
  hosts: frontend
  become: yes
  tasks:
    - name: disable default nginx
      ansible.builtin.command: dnf module disable nginx

    - name: enable nginx 1.24
      ansible.builtin.command: dnf module enable nginx:1.24 -y

    - name: install nginx        
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: remove html directory
      ansible.builtin.file:
        state: absent
        path: /usr/share/nginx/html

    - name: create html directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory
    
    - name: download frontend content
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
        dest: /tmp/frontend.zip

    - name: unzip frontend content
      ansible.builtin.unarchive:
        src: /tmp/frontend.zip
        dest: /usr/share/nginx/html

    - name: delete default nginx config
      ansible.builtin.file:
        state: absent
        path: /etc/nginx/nginx.conf

    - name: copy roboshop config
      ansible.builtin.copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: started   # use "restarted" if already running
        enabled: yes

    